pipeline {
    
    agent any 
    environment {
        IMAGE_TAG = "${BUILD_NUMBER}"
    }
     triggers { githubPush() }

    stages {
        stage('Validate Branch') {
            steps {
                script {
                    def branch = sh(script: "git rev-parse --abbrev-ref HEAD", returnStdout: true).trim()
                    if (branch == 'deploy') {
                        echo "Branch 'deploy' detected — skipping to prevent infinite loop."
                        currentBuild.result = 'SUCCESS'
                        return
                    }
                }
            }
        }
    
   
        
        stage('Checkout'){
           steps {
                git branch: 'main', credentialsId: 'Github', url: 'https://github.com/Maggi12-max/Jenkins-Zero-To-Hero.git'
           }
        }

        stage('Build Docker'){
            steps{
                script{
                    sh '''
                    echo 'Buid Docker Image'
                    docker build -t maggi19/cicd:${BUILD_NUMBER} -f python-jenkins-argocd-k8s/Dockerfile .
                    '''
                }
            }
        }

        stage('Push the artifacts'){
           steps{
                script{
                  withCredentials([usernamePassword(credentialsId: 'docker-cred', 
                                                 usernameVariable: 'DOCKER_USER', 
                                                 passwordVariable: 'DOCKER_PASS')]) {
                    sh '''
                      echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                      docker push maggi19/cicd:${BUILD_NUMBER}
                    '''
                }
            }
        }
      }
        
        stage('Checkout K8S manifest SCM'){
            steps {
                git credentialsId: 'Github', 
                url: 'https://github.com/Maggi12-max/Jenkins-Zero-To-Hero.git',
                branch: 'Deploy'
            }
        }
        
        stage('Update K8S manifest & push to Repo'){
            steps {
                script{
                    withCredentials([string(credentialsId: 'Git', variable: 'GITHUB_TOKEN')]) {
                        sh """
                        cat python-jenkins-argocd-k8s/deploy/deploy.yaml
                        sed -i "s#\\(image: .*:\\).*#\\1${BUILD_NUMBER}#g" python-jenkins-argocd-k8s/deploy/deploy.yaml
                        git add python-jenkins-argocd-k8s/deploy/deploy.yaml
                        git commit -am "update image to ${BUILD_NUMBER} [skip ci]"
                        git remote -v
                        git push https://${GITHUB_TOKEN}@github.com/Maggi12-max/Jenkins-Zero-To-Hero.git HEAD:Deploy
                        """                        
                    }
                }
            }
        }
    }
}

