pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { 
          image 'maven:3.8.1-adoptopenjdk-11'
          args '-v volume:/app/data'
        }
      }
      steps {
         sh 'mvn --version > /app/data/output.txt'
      }
    }
    stage('Front-end') {
      agent {
        docker { 
          image 'node:16-alpine'
          args '-v volume:/app/data'
        }
      }
      steps {
        sh 'node --version > /app/data/output.txt'
      }
    }
  }
}
